language: objective-c
osx_image: xcode9.2

before_install:
  - pod install --repo-update

script:
  - swiftlint
  - set -o pipefail
  - xcodebuild test -workspace JSwift.xcworkspace -scheme JSwift -sdk macosx ONLY_ACTIVE_ARCH=NO | xcpretty -c
