language: objective-c
osx_image: xcode9.2

before_install:
  - pod install --repo-update

script:
  - swiftlint
  - set -o pipefail
  - xcodebuild test -workspace JSON2SWIFT.xcworkspace -scheme JSON2SWIFT -sdk macosx ONLY_ACTIVE_ARCH=NO | xcpretty -c
after_success:
  - bash <(curl -s https://codecov.io/bash)
