language: objective-c
osx_image: xcode9.2

before_install:
  - pod repo update --silent

script:
  - swiftlint
  - set -o pipefail
  - xcodebuild test -workspace JSON2SWIFT.xcworkspace -scheme JSON2SWIFT -sdk macosx ONLY_ACTIVE_ARCH=NO | xcpretty -c
